# Generated by Django 4.1.2 on 2022-10-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationjudge',
            old_name='day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reservationjudge',
            name='month',
        ),
        migrations.RemoveField(
            model_name='reservationjudge',
            name='year',
        ),
    ]
