# Generated by Django 4.1.2 on 2022-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_management', '0002_rename_day_reservationjudge_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationjudge',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
